//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jqueryCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class floor
    {
        public int floor_id { get; set; }
        public string floor_name { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<decimal> rate { get; set; }
    }
}
