//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jqueryCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPerformance
    {
        public int ID { get; set; }
        public Nullable<int> EnglishScore { get; set; }
        public Nullable<int> MathScore { get; set; }
        public Nullable<int> ScienceScore { get; set; }
        public string Remarks { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
